'use client';
import {useState} from 'react';
import {Sparkles,Plus,ArrowUp,Image,Film,AudioLines,Wand2,ChevronDown,Upload} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {models} from '@/registry/models';
import {routeIntent} from '@/core/intent';
import {mockProvider} from '@/providers/mock';
import type {Category} from '@/core/types';
export function Choice({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(s:string)=>void}){return <label className="choice"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{options.map(x=><SelectItem key={x} value={x}>{x==='Automatic'?'Automático':x}</SelectItem>)}</SelectContent></Select></label>}
export function Composer({prompt,setPrompt,initialMode='Auto',adult=false,safety='Adulto',onSafetyChange,onGenerate,onUpload}:{prompt:string;setPrompt:(p:string)=>void;initialMode?:string;adult?:boolean;safety?:string;onSafetyChange?:(s:string)=>void;onGenerate:(category:Category,model:string,count:number)=>void;onUpload:()=>void}){
const [mode,setMode]=useState(initialMode);const [model,setModel]=useState('Automatic');const [quality,setQuality]=useState('1080p');const [ratio,setRatio]=useState('16:9');const [duration,setDuration]=useState('10s');const [count,setCount]=useState('1');const [advanced,setAdvanced]=useState(false);const intent=routeIntent(prompt);const category:Category=mode==='Auto'?intent.category:mode==='Edit'?'editing':mode.toLowerCase() as Category;const compatible=models.filter(m=>m.category===category);const resolvedModel=compatible.some(m=>m.id===model)?model:compatible.find(m=>m.id===intent.model)?.id||compatible[0]?.id||intent.model;
return <section className={'composer '+(adult?'adult-composer':'')} id="composer"><div className="composer-heading"><Sparkles size={18}/><strong>O que você quer criar hoje?</strong><span className="demo-label">DEMONSTRAÇÃO</span></div>{adult&&<div className="composer-safety"><span>Visibilidade: privada</span><Tabs value={safety} onValueChange={onSafetyChange}><TabsList>{['Seguro','Adulto','Todos'].map(s=><TabsTrigger value={s} key={s}>{s}</TabsTrigger>)}</TabsList></Tabs></div>}<textarea aria-label="Descreva sua criação" placeholder="Descreva sua ideia. Vamos dar vida à sua imaginação…" value={prompt} onChange={e=>setPrompt(e.target.value)}/><div className="composer-controls"><button className="upload-btn" aria-label="Enviar referência" onClick={onUpload}><Plus size={20}/></button><Tabs value={mode} onValueChange={setMode}><TabsList>{['Auto','Image','Video','Audio','Edit'].map((m,i)=>{const Icon=[Sparkles,Image,Film,AudioLines,Wand2][i];return <TabsTrigger key={m} value={m}><Icon size={14}/>{({Auto:'Auto',Image:'Imagem',Video:'Vídeo',Audio:'Áudio',Edit:'Editar'} as Record<string,string>)[m]}</TabsTrigger>})}</TabsList></Tabs>{!adult&&<a className="composer-adult-link" href="/adult">18+</a>}<div className="composer-options"><Choice label="Proporção" value={ratio} options={['16:9','1:1','9:16','4:3']} onChange={setRatio}/><Choice label="Qualidade" value={quality} options={['720p','1080p','2K']} onChange={setQuality}/><button className="primary generate" disabled={!prompt.trim()} onClick={()=>onGenerate(category,resolvedModel,Number(count))}>Gerar <Sparkles size={16}/></button></div></div><div className="composer-foot"><span>{prompt?`${mode==='Auto'?intent.intent:category==='image'?'TEXT_TO_IMAGE':category==='video'?'TEXT_TO_VIDEO':category==='audio'?'TEXT_TO_AUDIO':'IMAGE_EDIT'} · ${mockProvider.estimate(category,Number(count))} créditos demo`:'✦ Uma ideia, uma foto ou um pouco de curiosidade.'}</span><button onClick={()=>setAdvanced(!advanced)}>Opções <ChevronDown size={13}/></button></div>{advanced&&<div className="advanced-grid"><div className="mobile-quality"><Choice label="Qualidade" value={quality} options={["720p","1080p","2K"]} onChange={setQuality}/></div><Choice label="Modelo" value={model} options={['Automatic',...compatible.map(m=>m.id)]} onChange={setModel}/><Choice label="Quantidade" value={count} options={['1','2','4']} onChange={setCount}/>{['video','audio'].includes(category)&&<Choice label="Duração" value={duration} options={['5s','10s','30s']} onChange={setDuration}/>}<small>Opções preview only. Results use sample media.</small></div>}</section>}
